-- MySQL Script generated by MySQL Workbench
-- Mon Sep 10 01:11:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sitio1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sitio1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sitio1` DEFAULT CHARACTER SET utf8 ;
USE `sitio1` ;

-- -----------------------------------------------------
-- Table `sitio1`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Login` (
  `Nick_L` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Persona` (
  `Nick_U` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Fecha_Nac` DATE NULL,
  `Cel` VARCHAR(45) NULL,
  `Delegacion` VARCHAR(45) NULL,
  `Login_Nick_L` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Admon_Usua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Admon_Usua` (
  `Nick_AU` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Cel` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Tipo` (
  `idTipo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Login_Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Login_Tipo` (
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  `Tipo_idTipo` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Delegacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Delegacion` (
  `idDel` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Direccion` (
  `idDir` INT NOT NULL,
  `Colonia` VARCHAR(45) NULL,
  `CP` INT NULL,
  `Calle` VARCHAR(45) NULL,
  `No_int` INT NULL,
  `No_ext` INT NULL,
  `Delegacion_idDel` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Persona_Dir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Persona_Dir` (
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  `Direccion_idDir` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`AdmonU_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`AdmonU_Usuario` (
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  `Admon_Usua_Nick_AU` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Owner` (
  `Nick_O` VARCHAR(15) NOT NULL,
  `Persona_Nick_U` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Catalogo_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Catalogo_Servicios` (
  `idCS` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Servicio` (
  `idServicio` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Catalogo_Servicios_idCS` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Owner_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Owner_Ser` (
  `Owner_Nick_O` VARCHAR(15) NOT NULL,
  `Servicio_idServicio` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Admon_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Admon_Ser` (
  `Nick_AS` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Cel` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`AdmonSer_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`AdmonSer_Ser` (
  `Servicio_idServicio` INT NOT NULL,
  `Admon_Ser_Nick_AS` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Zona_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Zona_Trabajo` (
  `idZT` INT NOT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Delegacion` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Owner_ZT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Owner_ZT` (
  `Owner_Nick_O` VARCHAR(15) NOT NULL,
  `Zona_Trabajo_idZT` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Renter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Renter` (
  `Nick_R` VARCHAR(15) NOT NULL,
  `Persona_Nick_U` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Contrato` (
  `Clave` VARCHAR(20) NOT NULL,
  `Fecha` DATE NULL,
  `Hora` VARCHAR(45) NULL,
  `Especificaciones` VARCHAR(225) NULL,
  `Clausulas` VARCHAR(225) NULL,
  `Renter_Nick_R` VARCHAR(15) NOT NULL,
  `Renter_Persona_Nick_U` VARCHAR(15) NOT NULL,
  `Owner_Nick_O` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`AdmonSer_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`AdmonSer_Contrato` (
  `Admon_Ser_Nick_AS` VARCHAR(15) NOT NULL,
  `Contrato_Clave` VARCHAR(20) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Horario_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Horario_Trabajo` (
  `idHT` INT NOT NULL,
  `Dia` VARCHAR(45) NULL,
  `Hora` VARCHAR(45) NULL,
  `Owner_Nick_O` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Queja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Queja` (
  `id_Queja` INT NOT NULL,
  `Descripcion` VARCHAR(400) NULL,
  `Contrato_Clave` VARCHAR(20) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Pago` (
  `idPago` INT NOT NULL,
  `Banco` VARCHAR(45) NULL,
  `Fecha` VARCHAR(45) NULL,
  `Monto` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`Catalogo_Tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`Catalogo_Tarjetas` (
  `id_Tar` INT NOT NULL,
  `Pago_idPago` INT NOT NULL,
  `Persona_Nick_U` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio1`.`LoginTipo_Quejas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio1`.`LoginTipo_Quejas` (
  `Queja_id_Queja` INT NOT NULL,
  `Login_Tipo_Login_Nick_L` VARCHAR(15) NOT NULL,
  `Login_Tipo_Tipo_idTipo` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
